### ISSUE TITLE
Support having path level parameters

### ISSUE THREAD

**Issue by jszwedko** [westfieldlabs/apivore#59]
Currently apivore expects everything under a given route, e.g. `/posts`, to be a HTTP verb, but `parameters` is also supported (to specify parameters that are required by each verb under the path).

E.g.

```yml
...
paths:
  /posts/{id}:
    parameters:
      - name: id
        in: path
        type: integer
        required: true
    get:
      ...
    put:
      ...
...
```
