### ISSUE TITLE
Fails to pull swagger json

### ISSUE THREAD

**Issue by nblumoe** [westfieldlabs/apivore#94]
apivore does not succeed on pulling a swagger JSON. After not having had any success with the proper, local JSON, we tried the one of the Swagger Pet demo, which did not work either:

```
1) the API and tests all documented routes
     Failure/Error: subject { Apivore::SwaggerChecker.instance_for('http://petstore.swagger.io/v2/swagger.json') }
     
     RuntimeError:
       Unable to perform GET request for swagger json: http://petstore.swagger.io/v2/swagger.json - undefined method `call' for nil:NilClass
       Did you mean?  caller.
     # /Users/nblu/.rvm/gems/ruby-2.3.1@bit.abe-face/bundler/gems/apivore-275e799ea72c/lib/apivore/swagger_checker.rb:78:in `rescue in fetch_swagger!'
     # /Users/nblu/.rvm/gems/ruby-2.3.1@bit.abe-face/bundler/gems/apivore-275e799ea72c/lib/apivore/swagger_checker.rb:75:in `fetch_swagger!'
     # /Users/nblu/.rvm/gems/ruby-2.3.1@bit.abe-face/bundler/gems/apivore-275e799ea72c/lib/apivore/swagger_checker.rb:70:in `load_swagger_doc!'
     # /Users/nblu/.rvm/gems/ruby-2.3.1@bit.abe-face/bundler/gems/apivore-275e799ea72c/lib/apivore/swagger_checker.rb:64:in `initialize'
     # /Users/nblu/.rvm/gems/ruby-2.3.1@bit.abe-face/bundler/gems/apivore-275e799ea72c/lib/apivore/swagger_checker.rb:6:in `new'
     # /Users/nblu/.rvm/gems/ruby-2.3.1@bit.abe-face/bundler/gems/apivore-275e799ea72c/lib/apivore/swagger_checker.rb:6:in `instance_for'
     # ./spec/requests/api_spec.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/requests/api_spec.rb:12:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `call' for nil:NilClass
     #   Did you mean?  caller
```

We are on Rails 5.0.0
